name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

defaults:
  run:
    shell: bash


jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Check dependencies
        run: |
            go version
            go mod verify


  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          set -x
          go version
          mkdir -p testdata/test262
          cd testdata/test262
          git init
          git remote add origin https://github.com/tc39/test262.git
          git fetch origin --depth=1 72154b17fc99a26e79b2586960f059360d4ce43d
          git reset --hard 72154b17fc99a26e79b2586960f059360d4ce43d
          cd -
          go test
